FROM node:20-alpine

WORKDIR /app

RUN npm install -g prisma

COPY package*.json ./
RUN npm install

COPY .. .

RUN npx prisma generate


RUN npm run build

EXPOSE 3000

COPY dev-env/start-next.sh /app/start-next.sh
RUN chmod +x /app/start-next.sh

CMD ["/app/start-next.sh"]